### ISSUE TITLE
Error with pathgen

### ISSUE THREAD

**Issue by TH3xACE** [CravateRouge/bloodyAD#1]
First of all, thanks for this amazing project... which seems like a good alternative to aclpwn which has lib issues nowadays.... The error that I am having is when using pathgen.py.

neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureNotFound} {message: There is no procedure with the name `gds.shortestPath.dijkstra.stream` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.}

**Comment by CravateRouge** [comment]
`pathgen.py` is using the Dijkstra's algorithm of the GDS library of Neo4j. You have to [install](https://neo4j.com/docs/graph-data-science/current/installation/) the GDS plugin into Neo4j before using `pathgen.py`.

**Comment by TH3xACE** [comment]
Thanks... for your response. That was the issue.... Just one question ? if you run pathgen alone... there should be any output ?

**Comment by CravateRouge** [comment]
You're welcome :)

Do you mean `pathgen.py` without GDS or `pathgen.py` without `autobloody.py`?

**Comment by TH3xACE** [comment]
pathgen with GDS without autobloody ? just like aclpwn with the argument > -dry to have something like > (USER@TESTSEGMENT.LOCAL)-[MemberOf]->(GROUP@TESTSEGMENT.LOCAL)-[MemberOf]->(ANOTHER GROUP@TESTSEGMENT.LOCAL)-[WriteDacl]->(TESTSEGMENT.LOCAL)

**Comment by CravateRouge** [comment]
It generates a JSON file with the path but it's not meant to be readable by the user. I have a TODO on `autobloody.py` to add a simulate option but it's not done yet.
