### ISSUE TITLE
pathgen.py does not work with latest Dijkstra

### ISSUE THREAD

**Issue by GodMod** [CravateRouge/bloodyAD#14]
I am using the [Neo4j Graph Data Science Library 2.0.4](https://graphdatascience.ninja/neo4j-graph-data-science-2.0.4.zip)
When executing pathgen.py, it throws the following error:
```
neobolt.exceptions.CypherSyntaxError: Type mismatch: expected String but was Map (line 1, column 84 (offset: 83))
"MATCH (s {name:$source}), (t {name:$target}) CALL gds.shortestPath.dijkstra.stream({ sourceNode:s, targetNode:t, relationshipWeightProperty:'bloodycost', nodeProjection:'*', relationshipProjection:{all:{type:'*', properties:'bloodycost'}}}) YIELD path RETURN path"
```
This is because the call of `gds.shortestPath.dijkstra.stream` was changed. The first argument must be now a `graphName`, see https://neo4j.com/docs/graph-data-science/current/algorithms/dijkstra-source-target/
Moreover, the configuration options `nodeProjection`, `relationshipProjection` are not used anymore. Maybe because of the need to create a graph before calling the dijkstra stream.

**Comment by CravateRouge** [comment]
Thank you, should be fixed now.
