### ISSUE TITLE
comment: Error initializing SSL/TLS, data 0, v2580

### ISSUE THREAD

**Issue by TryA9ain** [CravateRouge/bloodyAD#15]
# comment: Error initializing SSL/TLS, data 0, v2580
`proxychains4 python bloodyAD.py -d missyou.com  -c ":dc.pem" -u 'test1234$' --host 192.168.1.2 setRbcd 'test1234$' 'dc$'`

<img width="626" alt="image" src="https://user-images.githubusercontent.com/51145610/172284916-a736dfd5-18a4-4e06-bb9c-e6170238e3aa.png">

**Comment by CravateRouge** [comment]
It seems SSL/TLS isn't enabled on your DC `192.168.1.2`. You can try to enable Certificate Services as specified on this [link](https://www.oreilly.com/library/view/active-directory-cookbook/0596004648/ch14s02.html) and it should enable all of what you need. 
But I'm surprised that you were able to request a certificate and can't do secure ldap.
