### ISSUE TITLE
How to set up RBCD？

### ISSUE THREAD

**Issue by Katsec** [CravateRouge/bloodyAD#17]
python bloodyAD.py -d spanning-tree.org  -c ":spanning-tree.pem" -u 'kattest$' --host 192.168.40.132 setRbcd "kattest$" "WIN-SJD97LJQLJP$"
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/47964489/180418827-cbdfd880-92a1-479c-81aa-e2a2d8036615.png">

thanks

**Comment by CravateRouge** [comment]
It works for me with the latest commit. Maybe it's a python version issue? Or a charset issue? I use python 3.10.5 with utf-8
