### ISSUE TITLE
ldap3.core.exceptions.LDAPNoSuchObjectResult

### ISSUE THREAD

**Issue by TryA9ain** [CravateRouge/bloodyAD#19]
# ldap3.core.exceptions.LDAPNoSuchObjectResult

i use 

`proxychains4 python bloodyAD.py -d xx.com -u test -p 'test' --host 10.1.1.1 setAttribute 'CN=wangleiaab,CN=Computers,DC=xx,DC=com' dNSHostName '["AD.xx.com"]'`

but error

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/51145610/182375955-dc727f76-c314-490d-9c21-770dda2cb4e2.png">

**Comment by CravateRouge** [comment]
As stated your dn `CN=wangleiaab,CN=Computers,DC=xx,DC=com` doesn't exist. Try with the sAMAccountName of the computer e.g `wangleiaab$` or do a `getObjectAttributes wangleiaab$ distinguishedName` to have the exact DN.
