### ISSUE TITLE
Bloodhound 4.2.0 released, new edges added

### ISSUE THREAD

**Issue by jsdhasfedssad** [CravateRouge/bloodyAD#20]
Hi again,

As always, your tool is amazing. No more PowerView! :)

As you may know, Bloodhound 4.2.0 was [released ](https://posts.specterops.io/introducing-bloodhound-4-2-the-azure-refactor-1cff734938bd)today. It supports new edges and they have also improved some already existing edges. Dare I ask for support for these? :) 

Thanks!

**Comment by CravateRouge** [comment]
Hi, 

Thank you :) and soon there will be no need to use LDAPS or SAMR for sensitive data (The PR is already made to ldap3 and I just need to change the appropriate calls)

Good to know, after reading it, here what you were already able to do:
- Read LDAPS password: `-s getObjectAttributes myPC$ ms-Mcs-AdmPwd`

And what I could update:
- Add Azure support
- Modify GetChanges and GetChangesAll with DCSync
- Add support for WriteAccountRestrictions when RBCD will be supported by autobloody.py

I let this issue open to remember and will add those tasks to my TODO list, thank you for the info :)
