### ISSUE TITLE
module "setGenericAll" remove permissions does not work 

### ISSUE THREAD

**Issue by trietend** [CravateRouge/bloodyAD#27]
The "setGenericAll" module with flag  "enable" set to "False" does not work for me. After adding the permissions them with the module it is not possible to  remove them.

https://github.com/CravateRouge/bloodyAD/blob/68408821b4f0ab280d7b45e2af621ee5268d4082/bloodyAD/utils.py#L266

"ace_haspriv" is always "false" here.

Therefore the remove is never reached.
https://github.com/CravateRouge/bloodyAD/blob/68408821b4f0ab280d7b45e2af621ee5268d4082/bloodyAD/utils.py#L282

Also this path is not taken, if the permissions are added twice.
https://github.com/CravateRouge/bloodyAD/blob/68408821b4f0ab280d7b45e2af621ee5268d4082/bloodyAD/utils.py#L272

**Comment by CravateRouge** [comment]
Try with v0.1.8 I changed a lot of things regarding security descriptor modifications in db27fa9

**Comment by trietend** [comment]
tested it on friday :D
works now, thanks a lot!

**Comment by CravateRouge** [comment]
Haha yes it can change very quickly

Great news! If you notice anything else don't hesitate to raise an issue or to make a suggestion.
