### ISSUE TITLE
setGenericAll seems to not working for OU

### ISSUE THREAD

**Issue by TH3xACE** [CravateRouge/bloodyAD#3]
Hi mate,

Can you please check for the SetGenericAll in the case of an OU. 

identity ->  OU where the current user has GenericAll or is Owner. 

The objective is to set GenericAll on a user that is in that same OU.
 
Looking to do something like 

--- Before          
                                                                
CompromisedUser -------GenericAll---------> Hero [OU] -------------contains-------------> TargetUser 

--- After
                                                               
CompromisedUser ---------GenericAll-------> Hero [OU] -------------GenericAll-------------> TargetUser 

Thanks again for your work :) ..... some of the functions do not give output but is working.... and some seems to work fine with DN but not other input type.... but great work... will surely help in RT ops...

**Comment by CravateRouge** [comment]
Normally if you set GenericAll for CompromisedUser on Hero and Hero contains TargetUser, inheritance from OU should give CompromisedUser GenericAll right on TargetUser. What do you observe? Any error output when applying setGenericAll on Hero?

Which functions do not give output?

Some functions are designed to work only with the DN, could you give me the name of the ones that you encountered?

**Comment by CravateRouge** [comment]
I will consider this issue as resolved thanks to only querying for the DACL of the SID now.
