### ISSUE TITLE
"get writable" errors with "Logon failure" in some cases

### ISSUE THREAD

**Issue by jsdhasfedssad** [CravateRouge/bloodyAD#37]
Using the command `get writable` sometimes fails with "Logon failure". I do not know exactly what triggers this but I get this error when authenticating using regular low priviledge accounts but not when authenticating using DAs so this may be related to privileges or lack there of.

In the screenshot you can see that the credentials for `domainuser1` are correct but that the command `get writable` still fails when authenticating using the same account. FYI. The account `domainuser1` does not have write rights of any sort to any object:
![getchildren4](https://user-images.githubusercontent.com/97032878/232819201-549bc5a6-883a-4873-a600-2eb00ef73e67.png)

Just to be certain, using the command `get writable` will list objects the authenticating account has GenericAll or GenericWrite rights on, correct? Perhaps WriteDACL too?

**Comment by CravateRouge** [comment]
@jsdhasfedssad The username is different between your two commands

@embargod Please open your own issue, it's a not related to the current issue

**Comment by jsdhasfedssad** [comment]
Ooops. You are correct. My bad!

What about the privileges? Will `get writable` list objects the authenticating account has GenericAll or GenericWrite rights on?Perhaps WriteDACL too?

**Comment by CravateRouge** [comment]
It will output you what you can write on the object or child if you can create a child to the object. If you want to know exactly what you can write on the object, use `--detail`. E.g. if it outputs a WRITE permission on nTSecurityDescriptor it means you have WRITEDACL .
If you want a Security Descriptor way of permissions you can alway use `get object --resolve-sd`

**Comment by jsdhasfedssad** [comment]
This is an interesting feature. Would you say it can partially replace Bloodhound/Sharphound? At least when it comes to identify and abuse edges that grants you write access?

Is there a way of using `get writable` in combination with `--detail` on a single object? Not only filtered by type.

It seems some attributes cannot be written to regardless of access rights. For example the attribute `badPwdCount`. BloodyAD is not showing that I have write access to that but I wanted to try it anyway using a DA account. Are some attributes "protected"?

I get the below error when trying the `--resolve-sd` command. The account I use is a DA:
![resolve-sd](https://user-images.githubusercontent.com/97032878/234322552-d7babf8a-091d-4c6b-80e2-d05aae33214b.png)

**Comment by CravateRouge** [comment]
It can help to identify interesting rights yes. Especially the write child which is not part of bloodhound edges if I'm not mistaken. But of course it doesn't replace the powerful graph db used by bloodhound.

You can't do it for a single object or use get object with attributes allowedAttributesEffective or allowedChildClassesEffective. You could also use resolve-sd.

For your error can you add a print(self.control_enum) before l.254 in utils.py and show me the output?

**Comment by CravateRouge** [comment]
@jsdhasfedssad can you confirm your issue is fixed? otype filtering on user should be fixed too
