### ISSUE TITLE
add computer - LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - ERROR_LOGON_FAILURE: Logon failure: Unknown user name or bad password. - bindResponse - None

### ISSUE THREAD

**Issue by embargod** [CravateRouge/bloodyAD#38]
Before i add another computers with `addcomputer` tool (via SAMR and LDAPS)
then `get writable` works okay
![image](https://user-images.githubusercontent.com/62397547/233662774-5e34621b-bb3d-438e-ac74-391024d55004.png)

But `add computer` false for reason
![image](https://user-images.githubusercontent.com/62397547/233662837-91dc2d3a-c819-43fe-86da-66cf49192f16.png)

**Comment by CravateRouge** [comment]
It's a NTLM logon failure, not related with computer creation. Your AD is refusing NTLM login with `pparker` with `Password1`. You can still try with another user and/or another bloody AD functionality such as `get object`.

**Comment by CravateRouge** [comment]
I think you should retry `add computer`

**Comment by embargod** [comment]
![image](https://user-images.githubusercontent.com/62397547/233666640-e754a7ef-db01-4eca-8ab6-ebfe63f8d23e.png)

**Comment by CravateRouge** [comment]
Try adding `-s` flag before `add computer`

**Comment by embargod** [comment]
same error

**Comment by CravateRouge** [comment]
I have no idea what's going on, you can still try kerberos

**Comment by embargod** [comment]
for you it works correctly?

**Comment by CravateRouge** [comment]
It does

**Comment by embargod** [comment]
okay, so shit happens, i need debug this

**Comment by CravateRouge** [comment]
Fixed with 3bc06f6e6fd5de4c698c794d84b847a994083305
